### ISSUE TITLE
ImportError when importing tensorflow

### ISSUE THREAD

**Issue by grovina** [benoitsteiner/tensorflow-opencl#37]
I wonder if you could help me with the following error when trying to import tensorflow freshly built from commit 49359bde.

`ImportError: libComputeCpp.so: cannot open shared object file: No such file or directory`

Everything seemed to work just fine during building and installing. Something like:

```
./configure

> Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3.5
> Please specify optimization flags to use during compilation [Default is -march=native]: 
> Do you wish to use jemalloc as the malloc implementation? [Y/n] 
> jemalloc enabled
> Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
> No Google Cloud Platform support will be enabled for TensorFlow
> Do you wish to build TensorFlow with Hadoop File System support? [y/N] N
> No Hadoop File System support will be enabled for TensorFlow
> Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] N
> No XLA JIT support will be enabled for TensorFlow
> Found possible Python library paths:
>   /usr/local/lib/python3.5/dist-packages
>   /usr/lib/python3/dist-packages
> Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.5/dist-packages]
> 
> Using python library path: /usr/local/lib/python3.5/dist-packages
> Do you wish to build TensorFlow with OpenCL support? [y/N] y
> OpenCL support will be enabled for TensorFlow
> Do you wish to build TensorFlow with CUDA support? [y/N] N
> No CUDA support will be enabled for TensorFlow
> Please specify which C++ compiler should be used as the host C++ compiler. [Default is ]: /usr/bin/gcc
> Please specify which C compiler should be used as the host C compiler. [Default is ]: /usr/bin/gcc
> Please specify the location where ComputeCpp for SYCL 1.2 is installed. [Default is /usr/local/computecpp]: 

bazel build -c opt --config=sycl //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
sudo pip3 install /tmp/tensorflow_pkg/tensorflow-0.12.1-cp35-cp35m-linux_x86_64.whl
```
I'm running Ubuntu 16.04 and the output of `bazel version` is:
```
Build label: 0.4.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 12:31:25 2016 (1482409885)
Build timestamp: 1482409885
Build timestamp as int: 1482409885
```
Thanks!

**Comment by lukeiwanski** [comment]
Do you have ComputeCpp CE 0.1.2 installed?

what is an output of `ls /usr/local/computecpp` ?

**Comment by krikru** [comment]
I just created a [pull request](https://github.com/benoitsteiner/tensorflow-opencl/pull/35/commits/d441fa84ec34f77d3517d0a243c9d26eab77b73a) for this problem – I had the same problem but I don't know if the cause is the same. Anyway, try adding the path to ComputeCpp's lib folder to your `LD_LIBRARY_PATH` in the environment you're running Python from to make Python find `libComputeCpp.so` and see if that solves the problem.

**Comment by bryanlimy** [comment]
I have the same problem but solved the import error as following

I have the `computecpp` folder stored at `/usr/local/computecpp`.
By default, `libComputeCpp.so` is under `computercpp/lib`.
So do `export LD_LIBRARY_PATH=/usr/local/computecpp/lib` to add the path
Now import should work.

**Comment by grovina** [comment]
`LD_LIBRARY_PATH` did work. I'll close the issue, thank you for the help!

@lukeiwanski `ls` gives _bin_, _doc_, _include_ and _lib_, by the way.

**Comment by ja3067** [comment]
I am having the same problem, even after setting the LD_LIBRARY PATH. The /usr/local/computecpp/lib directory contains the libComputeCpp.so file, but tensorflow is unable to find it. Tensorflow is freshly built, with the same build configuration as the OP, and the latest version of ComputeCpp was just downloaded today. I am running Ubuntu 16.04, which may be causing problems, but this seems like a simple issue. Any thoughts?

**Comment by krikru** [comment]
@ja3067 Maybe a silly question, but does the `LD_LIBRARY PATH` variable contain `/usr/local/computecpp/lib` in the shell in which TensorFlow fails to find `libComputeCpp.so`? Perhaps you added it to your `~/.bashrc` but forgot to start a new shell or re-source `~/.bashrc` afterwards.

**Comment by abhinav1697** [comment]
I have the same problem as ja3067 .
Even after setting the LD_LIBRARY PATH , tensorflow is not able to find the libComputeCpp.so file.
I have installed tensorflow from source on ubuntu 16.04. Bazel version is 0.5.2 , my installation steps are identical to grovina, only that I have enabled Hadoop file system support ,and Google cloud platform support additionally.

Here's the traceback of the error:

  File "server.py", line 6, in <module>
    from deep_reinforcement_learning import *
  File "/home/abhi/Tic-Tac-Toe-Machine-Learning-Using-Reinforcement-Learning/deep_reinforcement_learning.py", line 10, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libComputeCpp.so: cannot open shared object file: No such file or directory 

Any suggestion to correct this problem would be great.
