### ISSUE TITLE
404 Error Downloading Nightly

### ISSUE THREAD

**Issue by dylib** [benoitsteiner/tensorflow-opencl#45]
I'm getting a 404 Not Found error when trying to access the nightly build download:
```
https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-mac/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-0.12.1-py2-none-any.whl
```
Here's the error:
```
HTTP ERROR 404

Problem accessing /view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-mac/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-0.12.1-py2-none-any.whl. Reason:

    Not Found

Powered by Jetty://
```
Linked from: https://github.com/benoitsteiner/tensorflow-opencl

> 
> People who are a little more adventurous can also try our nightly binaries:
> 
>     Linux CPU-only: Python 2 (build history) / Python 3.4 (build history) / Python 3.5 (build history)
>     Linux GPU: Python 2 (build history) / Python 3.4 (build history) / Python 3.5 (build history)
>     Mac CPU-only: Python 2 (build history) / Python 3 (build history)
-->  Mac GPU: Python 2 (build history) / Python 3 (build history)
>     Android: demo APK, native libs (build history)

**Comment by benoitsteiner** [comment]
This could be related to our [recent build failures on Mac](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-mac/): the build have failed since Feb 12, so there is no build artifact to download.
