### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by TheOncomingStorm** [benoitsteiner/tensorflow-opencl#6]
What's the status of this? I'm building it from source(since I'm guessing that's the only option) but not sure if I'm doing it correctly. I know you have to add "config=cuda" if you're building for CUDA but not sure if there's a special config for OpenCL.  Also, I'm planning on using this with my Intel gfx GPU, will that be supported if I use beignet?

**Comment by benoitsteiner** [comment]
First, you need to download and install the compiler available at https://www.codeplay.com/products/computesuite/computecpp.

Then you need to call ./configure and make sure you answer YES when prompted for OpenCL support.

Last but not least, you need to call bazel with --config=sycl to compile the OpenCL kernels.
