### ISSUE TITLE
Anyway to run on AMDGPU-PRO driver?

### ISSUE THREAD

**Issue by Valentin4869** [benoitsteiner/tensorflow-opencl#73]
I've been trying to install this by following the guide [here](https://www.codeplay.com/portal/03-30-17-setting-up-tensorflow-with-opencl-using-sycl). Now the issue seems to be with installing the fglrx driver, but my GPU is no longer supported (RX460). I tried to install the fglrx driver anyway on Ubuntu 14.04.1 and 14.04.5 but as expected, it didn't work. And following the guide while skipping the fglrx installation part still doesn't work.

Can someone please confirm whether there is any way to get this to work on an AMD GPU that doesn't support fglrx? So far I've spent two days trying to get this to work.

**Comment by rodburns** [comment]
When you say it doesn't work what are the symptoms? Can you provide all your environment setup details and any logs that you get when building/running? Does clinfo show your GPU is working properly and have you used it with other software?

**Comment by rodburns** [comment]
Also this may help? https://github.com/benoitsteiner/tensorflow-opencl/issues/67

**Comment by Valentin4869** [comment]
Thanks for replying. The main issue is that fglrx is simply incompatible with my GPU. Everytime I try to install it and reboot, the gui is gone. I've tried this on 3 different Ubuntu versions. I forgot what the issue was when I skippd fglrx, but I gave up on this.

Also, thanks for the link, but it links back to a similar guide (looks exactly the same), which still relies on fglrx.
