### ISSUE TITLE
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: _ZN2cl4sycl7program30create_program_for_kernel_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKhiPPKcSt10shared_ptrINS0_6detail7contextEE

### ISSUE THREAD

**Issue by TheOncomingStorm** [benoitsteiner/tensorflow-opencl#8]
My build goes fine but when I import tensorflow I get the following. I'm doing this on Ubuntu 16.04 but I see this type of message on Gentoo when one of the packages has been compiled with gcc4.x and the one you're compiling was done with gcc5.x. I just checked and the version I compile without OpenCL works just fine. Any ideas? 

`ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: _ZN2cl4sycl7program30create_program_for_kernel_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKhiPPKcSt10shared_ptrINS0_6detail7contextEE`

**Comment by benoitsteiner** [comment]
We were trying to use OpenCL devices to process strings, which is a bad idea for many reason. This should be addressed now by https://github.com/benoitsteiner/tensorflow-opencl/commit/44f97e8fd3e110be977b753110739dc4f53c7477 and https://github.com/benoitsteiner/tensorflow-opencl/commit/0e19acedde840886621a4ccdea6c34936d6f0577

**Comment by gartnera** [comment]
I'm getting the same error on 810d6fe618f78e3c415c00a76d6c9a4365b4b82f. I'm building with the instructions from #6.

**Comment by lukeiwanski** [comment]
@gartnera, @TheOncomingStorm  could you please provide an output of computecpp_info ( binary in the same folder as compute++ ? As well what is the GCC version you guys are using?

**Comment by benoitsteiner** [comment]
This appears to be fixed, so I'm closing this issue. Please reopen if needed.
